---
# Audit the users on AIX systems
- name: audit the passwd file
  fetch:
    src=/etc/passwd
    dest=/tmp/{{ ansible_hostname }}/
    flat=yes

- name: audit the group file
  fetch:
    src=/etc/group
    dest=/tmp/{{ ansible_hostname }}/
    flat=yes

- name: audit the sudoers file
  fetch:
    src=/etc/sudoers
    dest=/tmp/{{ ansible_hostname }}/
    flat=yes

- name: audit the security roles file
  fetch:
    src=/etc/security/roles
    dest=/tmp/{{ ansible_hostname }}/
    flat=yes