---
# Audit the users on RedHat systems
- name: audit passwd file
  fetch:
    src=/etc/passwd
    dest={{ auditfile_save_dir }}/{{ ansible_hostname }}/
    flat=yes

- name: audit group file
  fetch:
    src=/etc/group
    dest={{ auditfile_save_dir }}/{{ ansible_hostname }}/

- name: audit sudoers file
  fetch:
    src=/etc/sudoers
    dest={{ auditfile_save_dir }}/{{ ansible_hostname }}/